import { createServerClient } from '@/lib/supabase/server'
import { NextResponse, type NextRequest } from 'next/server'

// Handles invite and recovery links generated by the admin panel.
// We build these URLs ourselves (bypassing Supabase's redirect allowlist),
// so we own the final redirect destination.
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const token_hash = searchParams.get('token_hash')
  const type = searchParams.get('type') as 'invite' | 'recovery' | null

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
    ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000')

  if (!token_hash || !type) {
    return NextResponse.redirect(`${siteUrl}/auth/error?reason=missing_params`)
  }

  const supabase = createServerClient()
  const { error } = await supabase.auth.verifyOtp({ token_hash, type })

  if (error) {
    console.error('[/auth/confirm] verifyOtp error:', error.message)
    return NextResponse.redirect(`${siteUrl}/auth/error?reason=${encodeURIComponent(error.message)}`)
  }

  // For recovery (password reset), send to the update-password page.
  // For invite (first login), send to the app.
  const destination = type === 'recovery' ? `${siteUrl}/auth/update-password` : `${siteUrl}/app`
  return NextResponse.redirect(destination)
}
